# Generated by Django 4.1.7 on 2023-05-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0003_communication_customer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='application_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
