# Generated by Django 4.1.7 on 2023-06-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0004_customer_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='application_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='identity_number',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='issuing_authority',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='residence_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='application_number',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
