# Generated by Django 4.1.7 on 2023-07-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0014_rename_fee_first_country_fee_first_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
