# Generated by Django 4.1.7 on 2023-07-23 20:40

from django.db import migrations, models
import musteri.models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0016_customer_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='file_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=musteri.models.get_upload_to),
        ),
    ]
