# Generated by Django 4.1.7 on 2023-07-23 20:58

from django.db import migrations, models
import django.db.models.deletion
import musteri.models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0017_customer_file_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='file_description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='uploaded_file',
        ),
        migrations.CreateModel(
            name='CustomerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to=musteri.models.get_upload_to)),
                ('file_description', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='musteri.customer')),
            ],
        ),
    ]
