# Generated by Django 4.2.7 on 2025-01-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0003_customer_company_customer_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appointment_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
