# Generated by Django 4.2.7 on 2025-01-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0004_customer_appointment_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='passport_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
