# Generated by Django 4.1.7 on 2023-06-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0005_customer_application_type_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='passport_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
