# Generated by Django 4.1.7 on 2023-07-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0006_alter_customer_passport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mail',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
