# Generated by Django 4.1.7 on 2023-07-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0009_alter_customer_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fixed_price', models.FloatField(blank=True, null=True)),
                ('is_boolean', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musteri.expenseitem')),
            ],
        ),
    ]
