# Generated by Django 4.1.7 on 2023-07-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0011_expense_delete_customerexpense_delete_expenseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
