# Generated by Django 4.1.7 on 2023-07-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0012_expenseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('fee_first', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_next', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAgeBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=200)),
                ('fee_first', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_second', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
