# Generated by Django 4.1.7 on 2023-07-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0013_country_insuranceagebracket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='fee_first',
            new_name='fee_first_year',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='fee_next',
            new_name='fee_next_year',
        ),
    ]
