# Generated by Django 4.1.7 on 2023-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0020_yapilacak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yapilacak',
            name='detay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
