# Generated by Django 4.1.7 on 2023-07-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0021_alter_yapilacak_detay'),
    ]

    operations = [
        migrations.AddField(
            model_name='yapilacak',
            name='tamamlandi',
            field=models.BooleanField(default=False),
        ),
    ]
