# Generated by Django 5.0.2 on 2024-03-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0025_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('basvuru_yapildi', 'Başvuru Yapıldı'), ('dosyalar_verildi', 'Dosyalar Verildi'), ('ptt_bekleniyor', 'PTT Bekleniyor'), ('kart_alindi', 'Kart Alındı'), ('tamamlandi', 'Tamamlandı')], default='basvuru_yapildi', max_length=20, verbose_name='Durum'),
        ),
    ]
