# Generated by Django 5.0.2 on 2024-03-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0027_alter_customer_application_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('basvuru_yapildi', 'Başvuru Yapıldı'), ('dosyalar_verildi', 'Değerlendirmede'), ('ptt_bekleniyor', 'Onay'), ('kart_alindi', 'Kart Postada'), ('tamamlandi', 'Tamamlandı')], default='basvuru_yapildi', max_length=20, verbose_name='Durum'),
        ),
    ]
