# Generated by Django 5.0.2 on 2024-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musteri', '0029_alter_customer_application_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_check_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Kontrol Tarihi'),
        ),
    ]
